- name: Download/unarchive docker
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.21.tgz
    dest: /tmp
    remote_src: yes
    
  
- name: copy binaries
  ansible.builtin.command: cp /tmp/docker/* /usr/bin/

- name: Start the Docker daemon
  ansible.builtin.command: dockerd &
