- name: Download/unarchive docker
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.21.tgz
    dest: /tmp
    remote_src: yes
    

- name: Copy file with owner and permissions
  copy:
    src: /tmp/docker/containerd 
    dest: /usr/bin/
    mode: '0775'
    remote_src: yes

- name: Start the Docker daemon
  ansible.builtin.command: dockerd &
