- name: Download/unarchive docker
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.21.tgz
    dest: /tmp
    owner: actia-admin
    group: actia-admin
    remote_src: yes
    force: no
    creates: /tmp/docker-20.10.21

- name: copy binaries
  ansible.builtin.copy:
    src: /tmp/docker-20.10.21/docker/*
    dest: /usr/bin/
    mode: 'u+x,g+x'

- name: Start the Docker daemon
  ansible.builtin.command: dockerd &
