- name: Download/unarchive docker
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.21.tgz
    dest: /tmp
    remote_src: yes
    

- name: Copy file with owner and permissions
  copy:
    src: /tmp/docker/{{item}}
    dest: /usr/bin/
    mode: '0775'
    remote_src: yes

  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v2
    - ctr
    - docker
    - dockerd
    - docker-init
    - docker-proxy
    - runc
- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{user}}"
    group: docker
    
- name: Apply the add to docker group
  ansible.builtin.command: newgrp docker & disown
  async: 45
  poll: 0
  
- name: Start the Docker daemon
  ansible.builtin.command: "nohup /usr/bin/dockerd> /dev/null 2>&1 &"

  

  
- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
