- name: Download/unarchive docker
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.21.tgz
    dest: /tmp
    remote_src: yes
    
- name: Start the Docker daemon
  ansible.builtin.command: ls /tmp


- name: Start the Docker daemon
  ansible.builtin.command: ls /tmp/docker-20.10.21/

- name: Start the Docker daemon
  ansible.builtin.command: ls /tmp/docker-20.10.21/docker/
  
- name: copy binaries
  ansible.builtin.copy:
    src: /tmp/docker-20.10.21/docker/*
    dest: /usr/bin/
    mode: 'u+x,g+x'

- name: Start the Docker daemon
  ansible.builtin.command: dockerd &
